[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=node_modules/@openzeppelin/', 'forge-std/=lib/forge-std/src']
fuzz_runs = 256
gas_reports = ["*"]
eth-rpc-url = 'https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c'
solc_version = '0.8.10'

# See more config options https://github.com/gakonst/foundry/tree/master/config
